### ISSUE TITLE
matplotlib cmap alongside palettable

### ISSUE THREAD

**Issue by martinfleis** [pysal/legendgram#9]
Hi,

is there a reason why only palettable color maps are allowed? I have made a tiny change to allow direct use of matplotlib cmaps to give it a bit more flexibility. For example, I am using `seaborn.light_palette` to get the color palette for choropleth and it works nicely with the changes in https://github.com/martinfleis/legendgram/tree/mpl_cmap. 

Did I miss anything? Can I prepare PR implementing this in a more robust way?

**Comment by ljwolf** [comment]
No, you're not missing anything; it should be OK, since we just need to construct the mpl colormap at l45 anyway!

I've done this locally alongside a bunch of small enhnacements I've used for papers... I have not had time to push them back up during the more general indecision about whether this moves into `pysal.splot`... 

So, maybe this makes sense for a new version?
1. a default for breaks (if `breaks=None`, color each bin according to its midpoint)
2. a default for pal (if `pal=None`, then grab the matplotlib default colormap)
3. introspecting f,ax rather than demanding them explicitly

Happy to review, merge, & release! @darribas @slumnitz, we'd talked about rolling the next release into splot. Regardless of if we do or not, let's do a final release of this package here?

**Comment by martinfleis** [comment]
Happy to hear that there's been some further development in `legendgram`. 

Changes in your fork look nice! I'll make a quick PR to use matplotlib colormaps, keeping in mind that your changes will come as well. 

Btw, to me it makes sense to have it as a part of splot.

**Comment by slumnitz** [comment]
@ljwolf and @martinfleis, I think making a final release sounds like a great thing to do nevertheless. Where would be the best place to integrate legendgram? We could either include it in `splot.mapping`, create a new namespace `splot.legendgram` or potentially give it a more open name in case we create some more legend related functionality, i.e. `splot.legends`? Happy to tackle this during a next sprint.
